compilar: ProyectoSO
	
ProyectoSO: ProyectoSO.c
	./ProyectoSO
ProyectoSO.c:
	gcc ProyectoSO.c -o ProyectoSO -lpthread
Auto:
	gcc structs/Auto.c -o Auto
Este:
	gcc structs/Este.c -o Este
Oeste:
	gcc structs/Oeste.c -o Oeste
Puente:
	gcc structs/Puente.c -o Puente

